### ISSUE TITLE
Fix clearfixes ...

### ISSUE THREAD

**Issue by mhulse** [mhulse/html-dummies#15]
``` css
.fix:before, .fix:after { content: " "; display: table; } .fix:after { clear: both; } .fix { *zoom: 1; }
```
