### ISSUE TITLE
Add these utility classes...

### ISSUE THREAD

**Issue by mhulse** [mhulse/html-dummies#4]
``` css
.fix { *zoom: 1; }
.fix:before,
.fix:after {
    content: "";
    display: table;
}
.fix:after { clear: both; }
.gone {
    display: none !important;
    visibility: hidden;
}
.off {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}
.ghost { visibility: hidden; }
.force {
    margin-top: -1px;
    margin-bottom: -1px;
    padding: 1px 0;
}
.nono { word-wrap: break-word; }
```
